from db import db

class Detection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image = db.Column(db.LargeBinary, nullable=False)
    filename = db.Column(db.Text, nullable=False)
    mimetype = db.Column(db.Text, nullable=False)
    beanGrade = db.Column(db.Text, nullable=False)
    veryDarkBrown = db.Column(db.Integer, default=0)
    brown = db.Column(db.Integer, default=0)
    partlyPurple = db.Column(db.Integer, default=0)
    totalPurple = db.Column(db.Integer, default=0)
    g1 = db.Column(db.Integer, default=0)
    g2 = db.Column(db.Integer, default=0)
    g3 = db.Column(db.Integer, default=0)
    g4 = db.Column(db.Integer, default=0)
    mouldy = db.Column(db.Integer, default=0)
    insectInfested = db.Column(db.Integer, default=0)
    slaty = db.Column(db.Integer, default=0)
    germinated = db.Column(db.Integer, default=0)

class TempDetection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image = db.Column(db.LargeBinary, nullable=False)
    filename = db.Column(db.Text, nullable=False)
    mimetype = db.Column(db.Text, nullable=False)
    beanGrade = db.Column(db.Text, nullable=False)
    veryDarkBrown = db.Column(db.Integer, default=0)
    brown = db.Column(db.Integer, default=0)
    partlyPurple = db.Column(db.Integer, default=0)
    totalPurple = db.Column(db.Integer, default=0)
    g1 = db.Column(db.Integer, default=0)
    g2 = db.Column(db.Integer, default=0)
    g3 = db.Column(db.Integer, default=0)
    g4 = db.Column(db.Integer, default=0)
    mouldy = db.Column(db.Integer, default=0)
    insectInfested = db.Column(db.Integer, default=0)
    slaty = db.Column(db.Integer, default=0)
    germinated = db.Column(db.Integer, default=0)